### ISSUE TITLE
Nav bar fixed with - - extra color on either end

### ISSUE THREAD

**Issue by Aleniras** [byuweb/byu-theme-components#271] opened 2017-07-14 18:19 UTC
Looks like when there's a fixed with, the nav bar is automatically filling with grey. Could we please extend it white all the way, regardless of whether or not the width is fixed?

<img width="1542" alt="screen shot 2017-07-14 at 12 17 36 pm" src="https://user-images.githubusercontent.com/26605197/28225069-894ceeba-688e-11e7-9a7f-c03acf086f11.png">

**Comment by bmorgan296** [comment] 2017-07-14 18:20
Duplicate of #261.

**Closed by bmorgan296** 2017-07-14 18:20 UTC

**Comment by bmorgan296** [comment] 2017-07-14 18:43
What is the URL for that website?

**Comment by Aleniras** [comment] 2017-07-14 18:43
https://lswebteam-new.byu.edu/Layouts/Left-Sidebar
