### ISSUE TITLE
Seach Bar Icon Functionality and Alignment/Style Issue

### ISSUE THREAD

**Issue by amaciasjr** [byuweb/byu-theme-components#437] opened 2018-12-05 16:50 UTC
# Description

*Tell us all about your problem or feature proposal.*
While reviewing on the https://pam-beta.byu.edu site with PAM's management, we realized that the header's search bar icon does not respond to a click. We also tested it on https://speeches.byu.edu. Also, after going filling out this issue, I realized that the search icon is not aligned with input field on a firefox browser.
**If the issue is with styling, please include screenshots!**

![image](https://user-images.githubusercontent.com/35348623/49529061-78b6b480-f872-11e8-848e-ddab769243c9.png)

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*
https://brand-beta.byu.edu/
https://pam-beta.byu.edu/
https://speeches.byu.edu/

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [x] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [ ] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [x] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by ThatJoeMoore** [comment] 2018-12-07 18:00
Looks like the functionality issue is the same as #436.

As for the UI issue, what version of Firefox are you running?  I can't replicate it in the latest version.

**Comment by kebowdog** [comment] 2018-12-11 16:00
The functionality issue should be fixed in #439. @amaciasjr can you let us know what version of Firefox you're running so we can confirm the issue is resolved?

**Comment by kebowdog** [comment] 2018-12-13 17:21
Closing because we can't reproduce the UI issue, and the functionality issue was fixed in #439. If you get more info on the UI issue feel free to reopen this.

**Closed by kebowdog** 2018-12-13 17:21 UTC

**Comment by jondeandrade** [comment] 2019-01-17 17:44
@kebowdog Hey, just found this alignment issue again on an iPad Pro on speeches.byu.edu, and on Firefox as well, version 64.0.2
