### ISSUE TITLE
[byu-menu] 'More' dropdown does not appear on Firefox

### ISSUE THREAD

**Issue by ThatJoeMoore** [byuweb/byu-theme-components#193] opened 2017-05-22 21:35 UTC
# Summary

When clicked on Firefox, the 'More' dropdown does not appear.

![screen shot 2017-05-22 at 3 12 40 pm](https://cloud.githubusercontent.com/assets/455981/26329326/ffaf7744-3f03-11e7-9ce2-2847edc535d4.png)

The issue does NOT appear on Chrome or Safari.  It may be present in IE/Edge, but it's a pain for me to test those on a Mac.

# Websites Affected

http://2017-components-demo.cdn.byu.edu/byu-menu.html

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

**Comment by ThatJoeMoore** [comment] 2017-05-22 22:07
It looks like it's due to this: https://github.com/byuweb/byu-theme-components/blob/3ee5966aceeb14b1d566c38c1fb963f33a441932/components/shared-styles/nav.scss#L41

When this runs in ShadyCSS browsers, the usage of this:

```
.slot-container ::slotted(*)
```

becomes

```
.byu-menu.slot-container > *
```

Which will also select the `byu-menu-more-menu` div.

I'm going to explore moving these into separate containers, because this could also cause other styling irregularities.

**Comment by ThatJoeMoore** [comment] 2017-05-22 22:53
I have a solution for this that is just waiting for #194 to be merged.

**Comment by bmorgan296** [comment] 2017-06-20 21:58
The problem has returned with the current version of components.

**Comment by bmorgan296** [comment] 2017-06-21 16:14
The cause of this issue is that the `.byu-menu-more-visible` is not applied to the more menu div.

**Comment by ThatJoeMoore** [comment] 2017-06-21 19:05
Digging though, I think I've found the cause of the problem.  When using the polyfills, as in Firefox, all changes to the Shadow DOM are asynchronous.  So, when we move an item from the main menu slot to the more slot, the `slotchange` event fires before the changes are actually reflected in the DOM.  By wrapping the slot change callback in a `setTimeout`, we can defer our reaction until the event queue has cleared and all of the async work the polyfill does has finished.  Then, all of the `querySelector`s we use will return the proper results.

We don't see this in Chrome and Safari because all Shadow DOM operations are synchronous in the native implementation.

**Comment by kebowdog** [comment] 2017-06-21 20:39
I've never seen setTimeout() called without a time before, so today I learned something new. That's pretty wild stuff. +1 to @ThatJoeMoore for working that out.

**Comment by ThatJoeMoore** [comment] 2017-06-21 20:40
Yeah, what it does is say "Hey, run this once your current task/event queue is clear" which usually happens within a few milliseconds.

**Comment by kebowdog** [comment] 2017-06-22 15:28
Fixed by PR #251

**Closed by kebowdog** 2017-06-22 15:28 UTC
Labels: browser-compatibility, bug
