### ISSUE TITLE
[byu-footer] footer columns take full width under 1024 px

### ISSUE THREAD

**Issue by jondeandrade** [byuweb/byu-theme-components#435] opened 2018-11-28 21:53 UTC
# Description
*Tell us all about your problem or feature proposal.*
Footer columns take the full width of the viewport too early, leaving a large amount of space to the right.
**If the issue is with styling, please include screenshots!**
![screen shot 2018-11-28 at 2 37 55 pm](https://user-images.githubusercontent.com/41493161/49183910-4ad5eb00-f31b-11e8-9cb3-ff5bd0f21a58.png)
![screen shot 2018-11-28 at 2 40 47 pm](https://user-images.githubusercontent.com/41493161/49184062-a011fc80-f31b-11e8-9091-8e9df252cf07.png)

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*
speeches.byu.edu
pam-beta.byu.edu

# Issue Type
*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Apple Safari
- [ ] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [x] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by Gi60s** [comment] 2018-11-30 17:46
@rburkey87 @kebowdog What is the expected behavior here? Should it go 2 columns first or go straight to one as the screen size gets smaller?

**Comment by kebowdog** [comment] 2018-11-30 17:55
In the past it's always gone to 2 columns for a bit, then to one once it got too small. I think it might be related to that "Flex: grow" that got removed last Monday.

**Comment by kebowdog** [comment] 2018-12-11 21:14
Ok, looks like it's not the flex grow that's the problem - at some point some margins got added to the footer-columns, but their calculated width didn't get updated. I'll update it so they go back to doing the two-column thing again.

**Comment by kebowdog** [comment] 2018-12-12 23:55
Fixed in #441

**Closed by kebowdog** 2018-12-12 23:55 UTC
