### ISSUE TITLE
[byu-footer] SVG in mobile doesn't push content down.

### ISSUE THREAD

**Issue by blakemorgan** [byuweb/byu-theme-components#420] opened 2018-10-29 17:57 UTC
# Description

SVG in mobile doesn't push content down.

**If the issue is with styling, please include screenshots!**

![image-1](https://user-images.githubusercontent.com/9389424/47669986-bf2d3b00-db71-11e8-89aa-023236bc8c25.jpg)

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [x] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

**Comment by kebowdog** [comment] 2018-10-29 18:42
@blakemorgan can you send me the markup you're using in the footer so I can reproduce this?

**Comment by ThatJoeMoore** [comment] 2018-10-29 18:52
@kebowdog Looks like he's just hitting the docs: http://2017-components-demo.cdn.byu.edu/byu-footer.html .  Look for "Double and triple-wide columns".

**Comment by kebowdog** [comment] 2018-10-29 19:31
Ok, I'm seeing it now. Thanks!

**Comment by blakemorgan** [comment] 2018-11-26 16:55
This bug only occurs with SVG's, not with other images. But it will happen with any SVG, not just the "don't panic" one.

**Comment by kebowdog** [comment] 2018-12-10 21:21
Fixed in #434

**Closed by kebowdog** 2018-12-10 21:21 UTC
Labels: bug
