### ISSUE TITLE
Float right or left messes with footer

### ISSUE THREAD

**Issue by Codac12** [byuweb/byu-theme-components#255] opened 2017-06-27 20:32 UTC
# Description

When something is defined as "float: left or right" it pushes the gray footer columns to the left or right

*Tell us all about your problem or feature proposal.*

**If the issue is with styling, please include screenshots!**

![screen shot 2017-06-27 at 2 31 25 pm](https://user-images.githubusercontent.com/25096102/27608629-6381df20-5b45-11e7-986a-11d9feca6a71.png)

# Websites Affected

*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know

**Comment by ThatJoeMoore** [comment] 2017-06-27 20:38
This is a duplicate of #210 .  Hopefully, we'll have a fix for it this week.

**Comment by ThatJoeMoore** [comment] 2017-07-06 02:49
@Codac12 We've got a fix for this in the testing stages.  If you change the theme components script tag from `https://cdn.byu.edu/byu-theme-components/latest/byu-theme-components.min.js` to `https://cdn.byu.edu/byu-theme-components/experimental/byu-footer-style-rewrite/byu-theme-components.min.js`, you can test the changes. Be warned, however, that as soon as the fixes are approved (https://github.com/byuweb/byu-theme-components/pull/248), the experimental version will disappear from the CDN.

**Comment by ThatJoeMoore** [comment] 2017-07-10 22:58
This has been merged, and is available in the `unstable` channel.  It should be released to production later this week.

**Closed by ThatJoeMoore** 2017-07-10 22:58 UTC
Labels: duplicate
